show_hide_home_wall
WildCodeSchool/reims-0918-js-hashtag-wall pull request #15
Opened 2018-10-15 14:07 UTC by benoit1521

2018-10-15 14:08 UTC, quentinsd approved these changes

2018-10-15 14:29 UTC, dadtmt requested changes

2018-10-15 14:29 UTC, dadtmt commented on src/App.js
> +          <Fragment>
You don't need Fragment if you have only one component

2018-10-15 14:29 UTC, dadtmt commented on src/App.js
> +      isTweetLaunch: false
a better name ?

2018-10-15 14:29 UTC, dadtmt commented on src/App.js
> +  handleHomePage() {
handleNewTag ?

2018-10-16 12:23 UTC, dadtmt approved these changes

2018-10-16 12:23 UTC, merged