Layoutgrid
WildCodeSchool/reims-0918-js-hashtag-wall pull request #9
Opened 2018-10-09 09:50 UTC by CorentinReims

2018-10-09 09:51 UTC, quentinsd approved these changes

2018-10-09 10:11 UTC, dadtmt requested changes

2018-10-09 10:11 UTC, dadtmt commented on src/App.css
> +     background-color: rgba(41, 41, 53, 0.4)!important;
is it only for component App or for a general style (in this case put it in index.css)

2018-10-10 07:53 UTC, dadtmt requested changes

2018-10-10 07:53 UTC, dadtmt commented on src/index.css
> +
you have duplicated the css in App.css ans index.css

2018-10-10 08:20 UTC, dadtmt approved these changes

2018-10-10 08:20 UTC, merged